name: SecondChance
version: '${project.version}'
main: com.secondchance.SecondChance
api-version: '1.19'

commands:
  SecondChance:
    description: On/Off Second Chance
    usage: /<command> [<false|true>]
  SecondChanceMessage:
    description: Set/Show message for Second Chance
    usage: /<command> [message]
  GiveSecondChance:
    description: Give a Second Chance for player
    usage: /<command> [player]